# Site settings
title: Rafael Valério - web designer
email: rafael.v90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rafael Valério - web designer e desenvolvedor front-end
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rafavalerio.com" # the base hostname & protocol for your site
twitter_username: rafaelvalerio
github_username:  rafaelv90
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
